### ISSUE TITLE
Task throws Exception because missing dependencies

### ISSUE THREAD

**Issue by RikuVirtanen** [CommunityHiQ/Frends.Community.Postgre#15]
Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
Could not load file or assembly 'System.Net.Sockets, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
These dependencies need to be added to the referencies in the projcs file.

**Comment by RikuVirtanen** [comment]
Previous PR didn't fix the issue with customer. Task is not using the System.Net.Sockets dll so the culprit might be another Task or something else entirely.

**Comment by helvertti** [comment]
The culprit seems to have been npqsql version. Rollback to version 4.0.10 was added where the known error hasn't broken yet.
