### ISSUE TITLE
Parameter can't be NULL

### ISSUE THREAD

**Issue by OssiGalkin** [CommunityHiQ/Frends.Community.Postgre#4]
It is possible to pass NULL to query if it is written straight in to query, but if it is passed through parameter it doesn't work.

Maybe a empty string could indicate that parameter is NULL? Atm empty string gives compile time time warning "Parameter 'PARAM' must have its value set". "Parameter 'PARAM' must have its value set", so that would not break anything.  Or just convert string "NULL" to NULL.

**Comment by eetuky** [comment]
NULL can be passed by settings the parameter to DBNull.Value .

**Comment by OssiGalkin** [comment]
Yeah, C# null to DBNull.Value conversion sounds best to me

**Comment by RikuVirtanen** [comment]
Fixed issue by creating parameter.Value check and converting it to DBNull.Value if null. #7
